
version: "3"
services:
  postgres:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgres
    env_file:
      - docker.env
 
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/root/.pgadmin
    env_file:
      - docker.env
 
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres

volumes:
  pgadmin-data:
  postgres-data: